india-ultimate/hub

pyproject.toml
In `pyproject.toml`, change python requirement to Python 3.10 and up
=> Change requirement to Python 3.10 and up

frontend/src/components/Membership.js, frontend/src/components/Player.js, frontend/src/utils.js
Added function `displayDate` in `utils.js` and used it in the html part of components while during membership and in player info. The format is human readable like so "1 June 2023".
=> registration: Add human readable dates in the pages

frontend/src/components/Player.js, frontend/src/components/VaccinationInformation.js, frontend/src/utils.js
Show state full name("Karnataka") instead of their shortened values("KA"). Similarly also for vaccine names instead of values.
=> home: Show state(and vaccination) name instead of shortened values

README.md, scripts/mask_email.js, scripts/update-sample-data.sh, server/fixtures/sample_data.json
=> Tournament and UC Fixtures

frontend/src/queries.js, server/api.py
Changes made as per discussion in #118
=> Reverse chronological order

frontend/src/components/TournamentManager.js, frontend/src/components/TournamentSchedule.js, frontend/src/components/tournament/MatchCard.js
=> schedule: Scroll to detailed card on match card click

frontend/package.json, frontend/src/components/TournamentManager.js, frontend/src/components/tournament/ReorderTeams.js, frontend/src/queries.js, frontend/yarn.lock
Fixes #155 
https://github.com/india-ultimate/hub/assets/39093537/93754aac-c0ff-4f6f-a9e3-645e00fe97b2
=> Reorder team seeding with drag/drop

frontend/src/components/tournament/MatchCard.js, frontend/tailwind.config.js
Needed for Mixed Regionals Bangalore based on their schedule
=> Add more colors for match card

frontend/src/components/TournamentMatch.js, frontend/src/components/TournamentTeam.js, frontend/src/components/tournament/SpiritScoreTable.js
=> Show matches in date sections

frontend/src/components/TournamentMatch.js
This is when a admin submits a score then suggested score does not exist hence we dont show spirit button which is not expected
=> spirit-score: Show submit button when match completed by staff

frontend/src/components/Login.js
@punchagan review and mergee :p lotta peeps having this prob xD
=> email-otp: Add email type to input and validate email

scripts/create-user.py, server/api.py, server/management/commands/import_players.py, server/management/commands/import_uc_registrations.py
=> emails: Convert emails to lowercase while storing/searching for users

frontend/src/components/TournamentMatch.js, server/api.py, server/schema.py, server/tests/test_api.py, server/tournament.py
=> Return all team ids where user has team admin access

frontend/src/components/Tournament.js, frontend/src/components/TournamentManager.js, frontend/src/queries.js, server/api.py, server/tests/test_api.py, server/tournament.py
fixes #183 
fixes #182 
fixes #181
=> Tournament Manager changes

frontend/src/components/TournamentTeam.js
=> team-matches: Fix bug in match day grouping

frontend/src/components/TournamentMatch.js, frontend/src/components/TournamentTeam.js, frontend/src/queries.js, server/api.py
@Joe2k pushing the changes from #214 in separate PRs to make reviewing and rebasing easier
=> Fetch matches for a particular team only

frontend/src/components/TournamentTeam.js, frontend/src/skeletons/Roster.js, frontend/src/skeletons/TournamentMatch.js, server/migrations/0050_alter_spiritscore_total.py
Adding skeletons for team page,
Adding reverse code for spirit score total migration
=> team-page: Add team page skeletons

frontend/src/components/App.js, frontend/src/components/ScrollUpButton.js, frontend/src/components/TournamentRules.js, frontend/src/components/TournamentSchedule.js, frontend/src/components/TournamentStandings.js, frontend/src/components/TournamentTeam.js, frontend/src/components/tournament/RulesMarkdownEditor.js, frontend/src/utils.js
=> Breadcrumb magic & Scroll to top

frontend/src/components/Breadcrumbs.js, frontend/src/components/Header.js, frontend/src/components/Tournament.js, server/api.py, server/schema.py, server/tests/test_api.py, server/tournament.py
=> Add link to player's team page

frontend/src/components/TournamentTeam.js, frontend/src/components/ValidateRoster.js, server/api.py
=> Show team roles in validation and roster page

frontend/src/components/TournamentRules.js
=> Ad Hoc Changes

frontend/src/components/TournamentTeam.js
https://upai.zulipchat.com/#narrow/stream/387757-tech-backend/topic/object.2Egroupby.20is.20not.20a.20function/near/406289560
=> Remove groupBy as it has limited availability

frontend/src/components/StyledMarkdown.js
=> Bug Fix for format not rendering properly in Rules page

frontend/src/components/Tournament.js, frontend/src/skeletons/Standings.js, frontend/src/utils.js
Fixes #242 
I'm showing this change only when the tournament has completed. Is there use in showing this during the tournament ? @Joe2k @punchagan
=> Show change in seeding in final standings

frontend/src/components/Accreditation.js, frontend/src/components/FileInput.js, frontend/src/components/InputLabel.js, frontend/src/components/UltimateCentralLogin.js, frontend/src/components/Vaccination.js, frontend/src/components/ValidateRoster.js, server/schema.py
=> Add UC Email for user and in validate roster

server/schema.py
reg: Remove uc id in player form to avoid it being updated
=> reg: Remove uc id in player form

frontend/src/components/App.js, frontend/src/components/Modal.js, frontend/src/components/Select.js, frontend/src/components/TeamRegistration.js, frontend/src/components/TournamentTeam.js, frontend/src/components/roster/EditRosteredPlayer.js, frontend/src/components/roster/RemoveFromRoster.js, frontend/src/components/roster/View.js, frontend/src/queries.js, server/api.py, server/schema.py
Since we are using UCRegistrations for UI, roles is a list of roles. Players and non-players are filtered based on "player" role in this list.
=> Rostering UI

frontend/src/components/Modal.js, frontend/src/components/roster/AddToRoster.js, frontend/src/utils.js, server/admin.py
- player-reg: Add clear button in search
- modal: Remove bg and add md width half
=> Search players fixes

frontend/src/components/Modal.js, frontend/src/components/TeamRegistration.js, frontend/src/components/popover/ErrorPopover.js, frontend/src/components/popover/SuccessPopover.js, frontend/src/components/roster/AddToRoster.js, frontend/src/components/series/AddToRoster.js, frontend/src/constants.js, frontend/src/index.css, frontend/src/queries.js, server/api.py, server/schema.py, server/series/api.py, server/series/utils.py, server/tournament/utils.py
=> Error toasts

server/api.py, server/schema.py, server/tests/test_api.py
For cases where player is 18+ but still has guardian.. Currently we are still not allowing them to sign but rather ask their guardian to sign
=> guardianship: Fix age validation

server/management/commands/import_players.py
Faced errors when trying to import players from the sheet, this PR removes whitespace from the player attributes
=> Remove whitespace from player attributes while importing players

.github/workflows/test.yml, hub/settings.py
(cherry picked from commit 9d235d9a0d0568418eb30c41b0beb980cd20ae9e)
=> email: Add zoho mail integration
